### PR TITLE
Adding Reducers and Actions completed

### PR DESCRIPTION
**Pull request by ometman**
I have added reducers and actions to the Bookstore Project.
- The duck pattern was used
- Implementation was on branch 'reducers-actions'
- Book and Categories directories were created in redux directory, with a store.js file.
- BooksSlice and CategoriesSlice were implemented.
- Book reducers to add and remove book were implemented
- Category reducers to check and return 'Under Construction' was implemented.
- Upon approval, the Provider will be wrapped on the App and dispatch of reducers and actions will be implemented
- Currently, the UI holds a state list of books.
- Linters checked and passed.

### CODE REVIEW

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @ometman 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Created  book's actions and reducer ✅ 
 - Installed and used  Redux Toolkit 👍🏿 




## Required Changes ♻️

- [ ] Kindly update the link to your issues page it shows a 404 error page 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ometman** [comment]
😄 Thanks

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @ometman,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

giphy (1)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ometman** [comment]
Thanks

**Pull request merged**
